/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Upload */
        post: operations["analyze_upload_analyze_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metric Catalog
         * @description `sector_id` is accepted case-insensitively; TECH_SAAS and RETAIL are the
         *     only sectors in MVP scope.
         */
        get: operations["metric_catalog_metrics__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Impact
             * @enum {string}
             */
            impact: "HIGH" | "MEDIUM" | "LOW";
            /**
             * Effort
             * @enum {string}
             */
            effort: "HIGH" | "MEDIUM" | "LOW";
        };
        /** Adjustment */
        Adjustment: {
            /** Target Metric Id */
            target_metric_id: string;
            /** Target Display Name */
            target_display_name: string;
            /**
             * Action
             * @enum {string}
             */
            action: "INCREASE" | "DECREASE";
            /**
             * Direction Symbol
             * @enum {string}
             */
            direction_symbol: "+" | "-";
            /** Current Value */
            current_value?: number | null;
            /**
             * Current Value Source
             * @enum {string}
             */
            current_value_source: "submitted" | "not_available";
            /** Target Value */
            target_value: number;
            /** Target Basis */
            target_basis: string;
            /** Delta */
            delta?: number | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "HIGH" | "MEDIUM" | "LOW";
            /** Rationale */
            rationale: string;
        } & {
            [key: string]: unknown;
        };
        /** Anomaly */
        Anomaly: {
            /** Anomaly Id */
            anomaly_id: string;
            /** Metric Id */
            metric_id: string;
            /** Metric Display Name */
            metric_display_name: string;
            /** Category */
            category: string;
            /** Severity Score */
            severity_score: number;
            severity_label: components["schemas"]["SeverityLabel"];
            deviation: components["schemas"]["DeviationDetail"];
            trend: components["schemas"]["TrendDetail"];
            /**
             * Correlated Anomalies
             * @default []
             */
            correlated_anomalies: string[];
            /** Noise Confidence */
            noise_confidence: number;
            /**
             * Context Tags
             * @default []
             */
            context_tags: string[];
            /** Natural Language Summary */
            natural_language_summary: string;
        } & {
            [key: string]: unknown;
        };
        /** AnomalyReport */
        AnomalyReport: {
            /**
             * $Schema
             * @default anomaly_report_v1
             */
            $schema: string;
            /** Company Id */
            company_id: string;
            sector_id: components["schemas"]["SectorId"];
            /** Analysis Timestamp */
            analysis_timestamp: string;
            reporting_period: components["schemas"]["ReportingPeriod"];
            company_profile_summary: components["schemas"]["CompanyProfileSummary"];
            /** Overall Health Score */
            overall_health_score?: number | null;
            /**
             * Anomalies
             * @default []
             */
            anomalies: components["schemas"]["Anomaly"][];
            /**
             * Non Anomalous Highlights
             * @default []
             */
            non_anomalous_highlights: components["schemas"]["HealthyHighlight"][];
            refusal?: components["schemas"]["RefusalDetail"] | null;
            metadata?: components["schemas"]["ReportMetadata"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ApiResponse
         * @description Envelope. Identical shape whether sync or polled — so we can switch
         *     without touching the frontend.
         */
        ApiResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "running" | "failed" | "refused";
            result?: components["schemas"]["EnrichedReport"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ParseWarning"][];
            error?: components["schemas"]["ErrorCode"] | null;
            timings?: components["schemas"]["Timings"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
            /**
             * Source Manifest
             * @default []
             */
            source_manifest: components["schemas"]["MetricSource"][];
            /** @default executive */
            persona: components["schemas"]["Persona"];
        };
        /** Body_analyze_upload_analyze_upload_post */
        Body_analyze_upload_analyze_upload_post: {
            /** File */
            file: string;
            /** Metadata */
            metadata: string;
            /** Mapping Overrides */
            mapping_overrides?: string | null;
        };
        /** Body_validate_validate_post */
        Body_validate_validate_post: {
            /** File */
            file: string;
            /** Metadata */
            metadata: string;
        };
        /** CompanyInput */
        CompanyInput: {
            /** Company Id */
            company_id: string;
            sector_id: components["schemas"]["SectorId"];
            company_metadata: components["schemas"]["CompanyMetadata"];
            reporting_period: components["schemas"]["ReportingPeriod"];
            /** Metrics */
            metrics: components["schemas"]["MetricEntry"][];
            /** Raw Text Context */
            raw_text_context?: string | null;
            persona?: components["schemas"]["Persona"] | null;
        };
        /** CompanyMetadata */
        CompanyMetadata: {
            /** Name */
            name: string;
            /** Founded Year */
            founded_year?: number | null;
            /** Employee Count */
            employee_count: number;
            /** Annual Revenue */
            annual_revenue?: number | null;
            revenue_band: components["schemas"]["RevenueBand"];
            /** Region */
            region: string;
        };
        /** CompanyProfileSummary */
        CompanyProfileSummary: {
            revenue_band: components["schemas"]["RevenueBand"];
            /** Employee Count */
            employee_count: number;
            /**
             * Region
             * @default NA
             */
            region: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CostEstimate
         * @description What the one LLM call cost, as far as we can honestly say.
         *
         *     C2-owned and on C2's envelope on purpose. The token count and model name
         *     come from C3's EnrichmentMetadata, but the *price* is ours to derive — and
         *     we already carry one unsigned addition to a shared model
         *     (EnrichmentMetadata.degraded_reason, Deviation #1). A second one would be
         *     worse manners than keeping our own derivation on our own envelope.
         *
         *     `estimated_usd` is None whenever we cannot stand behind a figure — an
         *     unpriced model, or no LLM call at all. It is never 0.0 as a stand-in for
         *     unknown. `basis` records how the figure was reached so it can be defended.
         */
        CostEstimate: {
            /** Llm Model */
            llm_model?: string | null;
            /** Tokens Used */
            tokens_used?: number | null;
            /** Estimated Usd */
            estimated_usd?: number | null;
            /** Basis */
            basis?: string | null;
        };
        /** DataPoint */
        DataPoint: {
            /** Period */
            period: string;
            /** Value */
            value: number;
            /**
             * Interpolated
             * @default false
             */
            interpolated: boolean;
        };
        /** DeviationDetail */
        DeviationDetail: {
            /** Observed Current */
            observed_current: number;
            /** Expected Value */
            expected_value: number;
            /** Expected Std */
            expected_std: number;
            /** Z Score */
            z_score: number;
            /** Percentile */
            percentile: number;
            direction: components["schemas"]["DeviationDirection"];
        } & {
            [key: string]: unknown;
        };
        /**
         * DeviationDirection
         * @enum {string}
         */
        DeviationDirection: "above_expected" | "below_expected" | "as_expected";
        /** EnrichedReport */
        EnrichedReport: {
            /**
             * $Schema
             * @default enriched_report_v1
             */
            $schema: string;
            anomaly_report: components["schemas"]["AnomalyReport"];
            /**
             * Prescriptions
             * @default []
             */
            prescriptions: components["schemas"]["Prescription"][];
            /**
             * Anomaly Clusters
             * @default []
             */
            anomaly_clusters: string[][];
            /**
             * Matched Cases
             * @default []
             */
            matched_cases: components["schemas"]["MatchedCase"][];
            narrative?: components["schemas"]["Narrative"] | null;
            metadata: components["schemas"]["EnrichmentMetadata"];
        } & {
            [key: string]: unknown;
        };
        /**
         * EnrichmentMetadata
         * @description degraded_reason — C2-PROPOSED v1.2, additive and optional. Not in the
         *     signed contract shape (Contract §6.2); flagged for announcement to C3
         *     alongside O7 (EnrichedReport sign-off still pending).
         *
         *     Deliberately Optional[str], not an enum: this field can be set by either
         *     side (C2 when it wraps a bare AnomalyReport after a C1/C3 failure; C3
         *     itself per Contract §6.7, e.g. an LLM failure it handles internally with
         *     no exception ever reaching C2). An enum would turn an unrecognised value
         *     from the other component into a ValidationError — a hard failure exactly
         *     where degradation was supposed to be graceful.
         *
         *     Conventional vocabulary (not enforced):
         *         C2 sets: c3_timeout | c3_failed | c3_contract_violation
         *         C3 sets: llm_failed | llm_timeout | case_match_failed
         *     Unknown values are logged and rendered generically, never rejected.
         */
        EnrichmentMetadata: {
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Tokens Used */
            llm_tokens_used?: number | null;
            /**
             * Processing Time Ms
             * @default 0
             */
            processing_time_ms: number;
            /**
             * Cases Searched
             * @default 0
             */
            cases_searched: number;
            /**
             * Cases Matched
             * @default 0
             */
            cases_matched: number;
            /**
             * Unmatched Anomaly Ids
             * @default []
             */
            unmatched_anomaly_ids: string[];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ErrorCode
         * @description Error-code vocabulary for ApiResponse.error (Phase1-Plan T1.5). C2-owned
         *     and always self-assigned — never parsed from an external component's
         *     output — so unlike EnrichmentMetadata.degraded_reason this is safe to
         *     type as an enum rather than a bare string.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "NO_USABLE_METRICS" | "C1_TIMEOUT" | "C1_FAILED" | "C1_UNAVAILABLE" | "C3_TIMEOUT" | "C3_FAILED" | "C3_CONTRACT_VIOLATION" | "INTERNAL_ERROR";
        /**
         * FeedbackCorrection
         * @description The specific corrections an analyst can make, from the four the critique
         *     names: "this was noise, suppress it", "more severe than the score
         *     suggests", and the root-cause correction workflow. Enumerated rather than
         *     free text so the log is aggregatable later — a pile of prose comments is
         *     not a feedback signal anyone can act on.
         * @enum {string}
         */
        FeedbackCorrection: "was_noise" | "severity_understated" | "severity_overstated" | "wrong_root_cause";
        /**
         * FeedbackRequest
         * @description What a user submits about a report they were just shown.
         *
         *     Scope honesty: this records a verdict, it does not retrain anything. The
         *     endpoint appends to a file. Nothing in the pipeline reads it back yet, and
         *     no claim to the contrary belongs in the UI or the deck — the Living
         *     Knowledge Base loop is roadmap, and this is its first hop.
         */
        FeedbackRequest: {
            /** Job Id */
            job_id: string;
            /**
             * Target
             * @default report
             * @enum {string}
             */
            target: "report" | "narrative" | "anomaly";
            /** Anomaly Id */
            anomaly_id?: string | null;
            verdict: components["schemas"]["FeedbackVerdict"];
            correction?: components["schemas"]["FeedbackCorrection"] | null;
            /** Comment */
            comment?: string | null;
        };
        /**
         * FeedbackResponse
         * @description Deliberately not an ApiResponse: feedback is not a pipeline run, and
         *     reusing that envelope would imply a job_id/status/result it does not have.
         */
        FeedbackResponse: {
            /** Recorded */
            recorded: boolean;
            /** Message */
            message: string;
        };
        /**
         * FeedbackVerdict
         * @enum {string}
         */
        FeedbackVerdict: "useful" | "not_useful";
        /**
         * Granularity
         * @enum {string}
         */
        Granularity: "monthly" | "quarterly" | "annual";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthyHighlight */
        HealthyHighlight: {
            /** Metric Id */
            metric_id: string;
            /** Metric Display Name */
            metric_display_name?: string | null;
            /**
             * Status
             * @default healthy
             */
            status: string | null;
            /** Percentile */
            percentile?: number | null;
            /** Note */
            note?: string | null;
            /** Observed Value */
            observed_value?: number | null;
            /** Expected Value */
            expected_value?: number | null;
            /** Context Tags */
            context_tags?: string[] | null;
            /** Natural Language Summary */
            natural_language_summary?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** InferredMetadata */
        InferredMetadata: {
            /** Granularity */
            granularity?: string | null;
            /**
             * Periods
             * @default 0
             */
            periods: number;
            /** Shape */
            shape?: ("wide" | "transposed" | "form") | null;
            /** Revenue Band */
            revenue_band?: string | null;
        };
        /**
         * MappingProposal
         * @description One resolved column from an uploaded file.
         */
        MappingProposal: {
            /** Source Label */
            source_label: string;
            /** Resolved Metric Id */
            resolved_metric_id?: string | null;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "exact" | "alias" | "normalized" | "unresolved";
            /** Unit Warning */
            unit_warning?: string | null;
            /**
             * Candidates
             * @default []
             */
            candidates: string[];
            /**
             * Sample Values
             * @default []
             */
            sample_values: number[];
        };
        /** MatchedCase */
        MatchedCase: {
            /** Case Id */
            case_id: string;
            /** Cluster Index */
            cluster_index: number;
            /** Similarity Score */
            similarity_score: number;
            /** Problem Description */
            problem_description: string;
            /** Root Causes */
            root_causes: string[];
            /** Recommended Actions */
            recommended_actions: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * MetricCatalogEntry
         * @description One metric as the system actually defines it — the machine-readable
         *     half of the KPI semantic contract.
         *
         *     `docs/kpi-semantic-contract.md` describes these in prose; this serves the
         *     same facts from `metric_config.yaml` at runtime, so a consumer can discover
         *     what the system accepts instead of reading a document and guessing. The
         *     prose doc and this endpoint therefore cannot drift: both are the YAML.
         */
        MetricCatalogEntry: {
            /** Metric Id */
            metric_id: string;
            /** Display Name */
            display_name: string;
            /** Unit */
            unit: string;
            /** Category */
            category: string;
            /** Direction */
            direction: string;
            /** Valid Min */
            valid_min?: number | null;
            /** Valid Max */
            valid_max?: number | null;
            /**
             * Accepted Aliases
             * @default []
             */
            accepted_aliases: string[];
        };
        /** MetricCatalogResponse */
        MetricCatalogResponse: {
            /** Sector Id */
            sector_id: string;
            /** Metric Count */
            metric_count: number;
            /** Metrics */
            metrics: components["schemas"]["MetricCatalogEntry"][];
            /**
             * Min Periods
             * @default {}
             */
            min_periods: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** MetricEntry */
        MetricEntry: {
            /** Metric Id */
            metric_id: string;
            granularity: components["schemas"]["Granularity"];
            /** Values */
            values: components["schemas"]["DataPoint"][];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /**
         * MetricSource
         * @description Provenance for one submitted metric (Stage 4 — critique P0 #2 / Req 2).
         *
         *     WHY THIS LIVES ON C2's ENVELOPE: the frontend only ever receives the
         *     EnrichedReport, so today it can see nothing about the CompanyInput that
         *     produced it. C2 holds that input. Deriving the manifest here means the
         *     lineage, grain and freshness reach the UI without a single change to C1's
         *     or C3's schemas.
         *
         *     WHAT IS REAL vs DECLARED — the distinction matters if a judge asks:
         *       * grain, as_of_period, period range, point counts, interpolated counts
         *         and confidence are all COMPUTED from the data actually submitted.
         *       * source_system is DECLARED by the user (or inferred from the uploaded
         *         filename). `source_basis` records which, so the label is never passed
         *         off as something the system verified.
         */
        MetricSource: {
            /** Metric Id */
            metric_id: string;
            /** Display Name */
            display_name?: string | null;
            /** Source System */
            source_system?: string | null;
            /**
             * Source Basis
             * @default unknown
             * @enum {string}
             */
            source_basis: "declared" | "upload_filename" | "unknown";
            /** Grain */
            grain: string;
            /** As Of Period */
            as_of_period?: string | null;
            /** First Period */
            first_period?: string | null;
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Interpolated Points
             * @default 0
             */
            interpolated_points: number;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Narrative */
        Narrative: {
            /** Situation Summary */
            situation_summary: string;
            /** Likely Root Causes */
            likely_root_causes: string[];
            /** Prioritized Actions */
            prioritized_actions: components["schemas"]["ActionItem"][];
            /** Positives */
            positives: string[];
        };
        /** ParseWarning */
        ParseWarning: {
            code: components["schemas"]["ParseWarningCode"];
            /** Metric Id */
            metric_id?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ParseWarningCode
         * @description Warning-code vocabulary, defined now so Phase 2 (parsing) and Phase 3
         *     (frontend) agree without a second conversation (Phase0-Plan T0.3).
         * @enum {string}
         */
        ParseWarningCode: "UNKNOWN_METRIC" | "UNIT_SCALE_SUSPECT" | "OUT_OF_RANGE" | "SHORT_SERIES" | "INTERPOLATED_POINTS" | "SECTOR_MISMATCH" | "AMBIGUOUS_MAPPING" | "SCHEMA_VALIDATION_ERROR" | "DATE_TRUNCATED" | "TWO_DIGIT_YEAR_FUTURE" | "AMBIGUOUS_NUMBER_FORMAT" | "MIXED_GRANULARITY" | "AMBIGUOUS_SHAPE" | "SERIES_TRIMMED" | "INTERPOLATION_HEAVY" | "CONSTANT_SERIES" | "SPARSE_SERIES" | "DUPLICATE_PERIOD" | "REFUSAL_LIKELY";
        /**
         * Persona
         * @description Who the report is being produced for.
         *
         *     ⚠️ C2-PROPOSED ADDITION TO THE SHARED SCHEMA — NOT SIGNED OFF.
         *     The only field C2 has added to this file. Recorded in full because the
         *     next person to read it needs the whole story.
         *
         *     WHY IT IS HERE. The problem statement requires at least two personas
         *     receiving different narratives. The narrative is C3's, generated from an
         *     AnomalyReport. For a persona to influence that prose it must reach the C3
         *     call, and the only route that does not breach C2's architectural boundary
         *     (`run_pipeline()` takes a CompanyInput and nothing else) is to carry it
         *     inside the CompanyInput. Hence a field on the shared contract.
         *
         *     WHY IT IS SAFE FOR C1. `ml_engine.models.input_schema.CompanyInput`
         *     declares no `model_config`, so Pydantic v2's default `extra="ignore"`
         *     applies: `orchestration/c1_adapter.py` dumps and revalidates through that
         *     model, and this field is dropped before C1 ever sees it. Verified against
         *     C1's source. C1 needs no change and cannot break on this.
         *
         *     HOW IT REACHES C3. Because C1 drops it, C2 re-attaches it to the
         *     AnomalyReport after C1 returns and before calling C3 (see
         *     `orchestration/pipeline.py`). C3's own AnomalyReport model sets
         *     `extra="allow"`, so it survives that crossing.
         *
         *     ⚠️ THIS FIELD DOES NOTHING ON ITS OWN — C3 MUST STILL ACT.
         *     `c3_engine/narrative.py` builds a single prompt and has no persona
         *     concept, so today the value arrives and is ignored: narrative prose is
         *     IDENTICAL for both personas. C3 must read `anomaly_report.persona` and
         *     vary the prompt before the requirement is actually met. Until then, do
         *     not claim persona-tailored narratives in the deck or the demo. C2's own
         *     persona work is a rendering/entitlement distinction — a different, and
         *     separately defensible, claim.
         *
         *     SEMANTIC CAVEAT. This describes the reader, not the company, so it sits
         *     oddly on CompanyInput. It is here because it is the only
         *     boundary-respecting route, not because it is the tidiest home.
         * @enum {string}
         */
        Persona: "executive" | "analyst";
        /** Prescription */
        Prescription: {
            /** Anomaly Id */
            anomaly_id: string;
            /** Prescribed Adjustments */
            prescribed_adjustments: components["schemas"]["Adjustment"][];
            /** Prescription Summary */
            prescription_summary: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * RefusalDetail
         * @description UNVERIFIED — confirm against C1 repo. Only `reason` is confirmed against
         *     C1's source; `message` and `suggested_resolution` are C2's provisional
         *     additions (Contract §5.1, O13). `extra="allow"` is mandatory per the
         *     contract so real fields we failed to predict aren't silently dropped.
         *
         *     C2's rendering logic must not depend on `message` being present — it
         *     generates fallback text from `reason` plus the original CompanyInput.
         *     Both provisional fields are therefore Optional even though the contract's
         *     prose shows `message` as a bare `str`.
         */
        RefusalDetail: {
            reason: components["schemas"]["RefusalReason"];
            /** Message */
            message?: string | null;
            /** Suggested Resolution */
            suggested_resolution?: string | null;
            /** Diagnostic Suggestion */
            diagnostic_suggestion?: string | null;
            /** Required Data */
            required_data?: string | null;
            /** Missing Metrics */
            missing_metrics?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RefusalReason
         * @enum {string}
         */
        RefusalReason: "no_metrics_submitted" | "low_data_confidence" | "insufficient_periods" | "contradictory_evidence";
        /** ReportMetadata */
        ReportMetadata: {
            /**
             * Model Version
             * @default 0.1.0-mvp
             */
            model_version: string;
            /** Synthetic Profile Version */
            synthetic_profile_version?: string | null;
            /**
             * Metrics Analyzed
             * @default 0
             */
            metrics_analyzed: number | string[];
            /**
             * Metrics With Anomalies
             * @default 0
             */
            metrics_with_anomalies: number | string[];
            /**
             * Metrics With Missing Data
             * @default 0
             */
            metrics_with_missing_data: number | string[];
            /**
             * Skipped Metrics
             * @default []
             */
            skipped_metrics: string[];
            /**
             * Processing Time Ms
             * @default 0
             */
            processing_time_ms: number;
        } & {
            [key: string]: unknown;
        };
        /** ReportingPeriod */
        ReportingPeriod: {
            type: components["schemas"]["Granularity"];
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /**
         * RevenueBand
         * @enum {string}
         */
        RevenueBand: "<1M" | "1M-10M" | "10M-100M" | ">100M";
        /**
         * SectorId
         * @enum {string}
         */
        SectorId: "TECH_SAAS" | "RETAIL";
        /**
         * SeverityLabel
         * @enum {string}
         */
        SeverityLabel: "INFO" | "WARNING" | "CRITICAL" | "SEVERE";
        /**
         * Timings
         * @description Wall-clock time C2's orchestrator spent per stage — distinct from each
         *     stage's own self-reported processing_time_ms (ReportMetadata /
         *     EnrichmentMetadata), which measures only that component's internal
         *     computation, not thread-pool or dispatch overhead.
         */
        Timings: {
            /** C1 Ms */
            c1_ms?: number | null;
            /** C3 Ms */
            c3_ms?: number | null;
            /** Total Ms */
            total_ms: number;
        };
        /** TrendDetail */
        TrendDetail: {
            direction: components["schemas"]["TrendDirection"];
            /** Slope */
            slope?: number | null;
            /** Acceleration */
            acceleration?: number | null;
            /** Periods Deviating */
            periods_deviating?: number | null;
            /** Values Over Time */
            values_over_time?: components["schemas"]["TrendPoint"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrendDirection
         * @enum {string}
         */
        TrendDirection: "improving" | "stable" | "deteriorating";
        /** TrendPoint */
        TrendPoint: {
            /** Period */
            period: string;
            /** Value */
            value: number;
            /** Z Score */
            z_score?: number | null;
            /**
             * Interpolated
             * @default false
             */
            interpolated: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * ValidateResponse
         * @description POST /validate's response shape (Phase2-Plan T2.6). Distinct from
         *     ParseResult — it never carries a company_input (validate stops before
         *     building one) and adds `inferred`/`ready`, which ParseResult has no use
         *     for elsewhere.
         */
        ValidateResponse: {
            /**
             * Proposals
             * @default []
             */
            proposals: components["schemas"]["MappingProposal"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ParseWarning"][];
            /**
             * Blocking Errors
             * @default []
             */
            blocking_errors: string[];
            /**
             * @default {
             *       "periods": 0
             *     }
             */
            inferred: components["schemas"]["InferredMetadata"];
            /**
             * Ready
             * @default false
             */
            ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_upload_analyze_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_upload_analyze_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_catalog_metrics__sector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
